Change default cost limit 30 $
lifebit-ai/cloudos-cli pull request #102
Opened 2022-10-24 11:21 UTC by egenc

This PR is intended for setting the default cost limit to 30$ to prevent any leakage.

2022-10-24 12:44 UTC, dapineyro requested changes
Hi @egenc , thanks for all the changes. There is still one change required in `click` defaults.

In addition, please, change all the `v1.1.0` references to `v.1.1.1` in `README.md`

2022-10-24 12:44 UTC, dapineyro commented on cloudos/__main__.py
>                default=-1)
```suggestion
              default=30.0)
```

2022-10-28 10:38 UTC, danielboloc commented
Hi @egenc, looks good. A few suggestions for the PR:

- It would be great to include the cloudOS tests in the PR description. I tested the new Docker image `quay.io/lifebitaiorg/cloudos-cli:v1.1.1` with these jobs:

  - https://cloudos.lifebit.ai/app/jobs/635baadee52b8f015599a01b -> had a `--cost-limit 0.05` and completed succesfully (total cost was $0.0212)
  - https://cloudos.lifebit.ai/app/jobs/635bac5ae52b8f015599a15b (the same parameters as above) -> had a `--cost-limit 0.01` and therefore failed/aborted. It was nice that it send me an email at 80% of reaching the cost limit and one after the limit was reached.

On the cloudOS platform I saw the second job was aborted, but I could not find in the log that the cost limit was exceeded.

So the new image `quay.io/lifebitaiorg/cloudos-cli:v1.1.1` does work properly.

2022-10-31 20:25 UTC, cgpu approved these changes

2022-11-03 11:53 UTC, cgpu requested changes
@egenc Change the version and add 1.2.1 it's a small patch

2022-11-03 17:25 UTC, dapineyro approved these changes
All the changes needed for version bumping from `v1.2.0` to `v1.2.1` were made. LGTM!

2022-11-03 20:55 UTC, cgpu approved these changes

2022-11-04 08:35 UTC, merged