Bumps version to 1.2.0
lifebit-ai/cloudos-cli pull request #105
Opened 2022-10-31 20:27 UTC by cgpu

Adds better handling for SSL verification.

2022-10-31 20:35 UTC, cgpu commented on README.md
> +Usage: python -m cloudos job run [OPTIONS]
```Suggestion
Usage: python -m cloudos job run [OPTIONS]

> NOTE: You may need to include the folder of the local clone of the `cloudos-cli` repo folder in `PATH` to be able to use the command `cloudos` without calling python, for example: `export PATH="~/path-of-cloudos-cli/:$PATH"`. This is required only if the installation location is not already included in `PATH`.
```

2022-10-31 20:36 UTC, cgpu commented on README.md
> +Usage: python -m cloudos job run [OPTIONS]
```Suggestion
Usage: cloudos job run [OPTIONS]
```

2022-11-02 17:11 UTC, dapineyro requested changes
Looks good, only two minor changes in README.md

2022-11-02 17:11 UTC, dapineyro commented on README.md
>  __Date:__ 2022-07-28\
```suggestion
__Date:__ 2022-10-28\
```

2022-11-02 17:11 UTC, dapineyro commented on README.md
> +> NOTE: To be able to call the `cloudos` executable, ensure that the local clone of the `cloudos-cli` folder is included in the `PATH` variable ,using for example the command `export PATH="/aboslut/p
```suggestion
> NOTE: To be able to call the `cloudos` executable, ensure that the local clone of the `cloudos-cli` folder is included in the `PATH` variable ,using for example the command `export PATH="/absolute/path/to/cloudos-cli:$PATH"`.
```

2022-11-02 17:20 UTC, cgpu commented
> Looks good, only two minor changes in README.md

thank you @dapineyro, addressed both, feel free to squash on your end!

2022-11-02 17:21 UTC, dapineyro approved these changes
LGTM! :+1:

2022-11-02 17:24 UTC, merged