test:  adds tests for 'get_workflow_list'
lifebit-ai/cloudos-cli pull request #117
Opened 2022-11-23 19:28 UTC by danielboloc

# Overview

Test the function `get_workflow_list` from `cloudos.clos`

Uses the `mock` and `responses` python packages to mock HTTP GET requests.

The test has the following functions each testing a different part:

- `test_get_workflow_list_correct_response` -> test if the function returns `requests.models.Response` and the `status_code` of the response is `200`

- `test_get_workflow_list_incorrect_response` -> test if the function raises the error `BadRequestException`

# Running the test

```console
python -m pytest -v tests/test_get_job_list.py
```

The response should be that all 2 tests have passed:

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/6720677/203631188-cf305fd7-e039-48b1-986a-5f44ef4b07a9.png">

2022-11-25 14:58 UTC, dapineyro requested changes
Great PR @danielboloc ! I just left some minor style comments. In addition, I'm a bit concerned about the use of `tests/test_data/process_job_list_initial_json.json` for mocking the server response. In this case, we are getting a "workflow list", not a job list. But for the scope of this testing function it's not relevant at all, so it's ok :+1:

Please, also remember to merge with `dev` and move the script to the `test_clos` folder.

2022-11-25 14:58 UTC, dapineyro commented on tests/test_get_workflow_list.py
> +import requests_mock
```suggestion
```
Not used

2022-11-25 14:58 UTC, dapineyro commented on tests/test_get_workflow_list.py
> +
```suggestion


```
Two blank lines

2022-11-25 14:58 UTC, dapineyro commented on tests/test_get_workflow_list.py
> +
```suggestion


````
Two blank lines

2022-11-25 14:58 UTC, dapineyro commented on tests/test_get_workflow_list.py
> +    # start cloudOS service
```suggestion
    # start cloudOS service
```
Trailing whitespace

2022-11-25 14:58 UTC, dapineyro commented on tests/test_get_workflow_list.py
> +        response = clos.get_workflow_list(WORKSPACE_ID)
```suggestion
        clos.get_workflow_list(WORKSPACE_ID)
```
Variable not used

2022-12-12 20:25 UTC, danielboloc commented
@dapineyro thanks for the review! I have updated the input file to `tests/test_data/workflows/workflows.json` and applied the suggestions

2022-12-16 12:26 UTC, dapineyro approved these changes
LGTM! :+1: Please, before merging, update the branch to `dev` and be sure that the tests still run correctly

2022-12-16 12:56 UTC, danielboloc commented
Thanks @dapineyro! Updated dev branch and tests still work

2022-12-16 12:56 UTC, merged