Pytest added for function process_workflow_list
lifebit-ai/cloudos-cli pull request #118
Opened 2022-11-24 08:17 UTC by egenc

Purpose of this PR is to add tests for the function`Cloudos.process_workflow_list` in CloudOS. 

Test data is obtained from `Cloudos.process_workflow_list` function and values are masked as `XxXXx`.
Test data:
- tests/test_data/process_workflow_list_initial_request.json
- tests/test_data/process_workflow_list_results.csv
- tests/test_data/process_workflow_list_results_FULL.csv

Tests are made for checking how the function `process_workflow_list` operating:
- `test_process_workflow_list` to check `all_fields=False` (specific columns)
- `test_process_workflow_list_all_fields` to check `all_fields=True` (all columns)

To run the test:
```
python3 -m pytest -s -v
```
Expected output:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/25952802/203729089-0148ef06-2e15-4421-85d3-e0b14432f78f.png">

2022-11-25 08:44 UTC, danielboloc reviewed
@egenc looks good, I have left some tiny suggestions regarding doc strings and function names

2022-11-25 08:44 UTC, danielboloc commented on tests/test_clos/test_process_workflow_list.py
> +
```suggestion

```

2022-11-25 08:44 UTC, danielboloc commented on tests/test_clos/test_process_workflow_list.py
> +
```suggestion

```

2022-11-25 08:44 UTC, danielboloc commented on tests/test_clos/test_process_workflow_list.py
> +def test_process_workflow_list(mocked_requests_get):
```suggestion
def test_process_workflow_list_all_fields_false(mocked_requests_get):
    """Test function parameter 'all_fields=False'"""
```

2022-11-25 08:44 UTC, danielboloc commented on tests/test_clos/test_process_workflow_list.py
> +def test_process_workflow_list_all_fields(mocked_requests_get):
```suggestion
def test_process_workflow_list_all_fields_true(mocked_requests_get):
    """Test function parameter 'all_fields=True'"""
```

2022-11-25 14:08 UTC, danielboloc approved these changes

2022-11-25 15:43 UTC, dapineyro requested changes
Thanks @egenc ! The code is great, just some minor style suggestions. Regarding the data you added in `test_data`, could it be possible to trim it to just contain one entry (one workflow)?

In addition, I observed that the structure of `process_workflow_list_initial_request.json` is not identical to the real JSON: you have changed the nested levels by using `.` notation. It does not affect the current function, as it's doing an equivalent `pandas.json_normalize()` but the contents of the function may change in the future, so it would be better to have a more realistic input.

2022-11-25 15:43 UTC, dapineyro commented on tests/test_clos/test_process_workflow_list.py
> +import requests, json
```suggestion
import requests
import json
```
Please, use one import per line

2022-11-25 15:43 UTC, dapineyro commented on tests/test_clos/test_process_workflow_list.py
> +
```suggestion


```
Two blank lines

2022-11-25 15:43 UTC, dapineyro commented on tests/test_clos/test_process_workflow_list.py
> +
```suggestion


```
Two blank lines

2022-11-25 15:43 UTC, dapineyro commented on tests/test_clos/test_process_workflow_list.py
> +
```suggestion


```
Two blank lines

2022-11-30 10:58 UTC, dapineyro requested changes
This one looks great @egenc . Just check the unresolved conversation and also the new suggestion

2022-11-30 10:58 UTC, dapineyro commented on tests/test_clos/test_process_workflow_list.py
> +
```suggestion
```

2022-12-02 16:56 UTC, dapineyro requested changes
Thanks @egenc . Only two very minor suggestions to check :+1:

2022-12-02 16:56 UTC, dapineyro commented on tests/test_clos/test_process_workflow_list.py
> +"""pytest for fucntion process_workflow_list"""
```suggestion
"""pytest for method Cloudos.process_workflow_list"""
```
Although it's not really necessary to add this docstring to this simple file.

2022-12-02 16:56 UTC, dapineyro commented on tests/test_clos/test_process_workflow_list.py
> +
```suggestion
```

2022-12-16 12:19 UTC, dapineyro approved these changes
LGTM! :+1:

2022-12-16 12:54 UTC, merged