Pytest added for function project_id
lifebit-ai/cloudos-cli pull request #120
Opened 2022-11-29 19:33 UTC by egenc

Purpose of this PR is to add tests for the functionCloudos.process_workflow_list in CloudOS.

Test data:
```
tests/test_data/process_job_list_initial_json.json
```

Tests are made for checking if the function project_id working as intended:
```
test_job_project_id
```
To run the test:
```
python3 -m pytest -s -v
```
Expected Output:
<img width="465" alt="image" src="https://user-images.githubusercontent.com/25952802/204630459-80784f3d-f073-4bf7-ac1f-b0aa16ffae44.png">

2022-11-30 11:22 UTC, dapineyro requested changes
@egenc The function tested here, was already added here: https://github.com/lifebit-ai/cloudos-cli/pull/116 Please, close this PR.

2022-12-01 11:25 UTC, dapineyro requested changes
Thanks @egenc . Please, take a look at my suggestions when you have time.

2022-12-01 11:25 UTC, dapineyro commented on tests/test_clos/test_project_id.py
> +import requests
```suggestion
```
These imports can be removed as they are not used

2022-12-01 11:25 UTC, dapineyro commented on tests/test_clos/test_project_id.py
> +
```suggestion


```

2022-12-01 11:25 UTC, dapineyro commented on tests/test_clos/test_project_id.py
> +        workflow_name=WORKFLOW_NAME)
```suggestion
    job = Job(apikey=APIKEY,
              cloudos_url=CLOUDOS_URL,
              workspace_id=WORKSPACE_ID,
              cromwell_token=None,
              project_name=PROJECT_NAME,
              workflow_name=WORKFLOW_NAME)
```

2022-12-01 11:25 UTC, dapineyro commented on tests/test_clos/test_project_id.py
> +    assert isinstance(project_id, str) and len(project_id) > 0
```suggestion
    assert project_id == '1234bc123125'
```
I think it's better to check for the known value of the project_id. Also, I'd suggest to change it in `projects.json` to something more informative than 'XXX' (e.g.: '1234bc123125')

2022-12-01 11:25 UTC, dapineyro commented on tests/test_data/projects.json
> +        "_id": "XXX",
```suggestion
        "_id": "1234bc123125",
```
Change it for something unique in the JSON to be more informative

2022-12-02 17:09 UTC, dapineyro requested changes
Thanks @egenc ! Only check that minor suggestion about the `docstring`

2022-12-02 17:09 UTC, dapineyro commented on tests/test_clos/test_project_id.py
> +"""Pytest added for checking project_id"""
```suggestion
"""Pytest added for checking Job.project_id"""
```
Not really required as the filename is quite self-explanatory.

2022-12-16 11:40 UTC, danielboloc approved these changes
Looks good @egenc!

2022-12-16 12:11 UTC, dapineyro approved these changes
LGTM! :+1:

2022-12-16 12:16 UTC, merged