pytest added for output workflow_id
lifebit-ai/cloudos-cli pull request #121
Opened 2022-11-30 07:52 UTC by egenc

Purpose of this PR is to add tests for the functionCloudos.process_workflow_list in CloudOS.

Test data:
```
tests/test_data/process_job_list_initial_json.json
```
Tests are made for checking if the function workflow_id working as intended

To run the test:
```
python3 -m pytest -s -v
```
Expected Output:
<img width="430" alt="image" src="https://user-images.githubusercontent.com/25952802/204738292-e3793fac-3756-4b3c-a94a-3c41fe338331.png">

2022-12-02 17:25 UTC, dapineyro requested changes
Thanks @egenc ! I left some minor comments about the style. In addition, as the other functions for `Job` objects, please, move the file to `tests/test_jobs`.

2022-12-02 17:25 UTC, dapineyro commented on tests/test_clos/test_workflow_id.py
> +"""pytest is added for checking workflow_id"""
```suggestion
"""pytest is added for checking Job.workflow_id"""
```
No really needed though.

2022-12-02 17:25 UTC, dapineyro commented on tests/test_clos/test_workflow_id.py
> +
```suggestion


```

2022-12-02 17:25 UTC, dapineyro commented on tests/test_clos/test_workflow_id.py
> +        workflow_name=WORKFLOW_NAME)
```suggestion
    job = Job(apikey=APIKEY,
              cloudos_url=CLOUDOS_URL,
              workspace_id=WORKSPACE_ID,
              cromwell_token=None,
              project_name=PROJECT_NAME,
              workflow_name=WORKFLOW_NAME)
```

2022-12-12 09:27 UTC, egenc commented
thanks @dapineyro ! please check the changes.

2022-12-16 12:14 UTC, dapineyro approved these changes
LGTM! :+1:

2022-12-16 12:21 UTC, merged