Pytest added for function ssl_selector
lifebit-ai/cloudos-cli pull request #122
Opened 2022-12-01 09:53 UTC by egenc

Purpose of this PR is to add tests for the function `__main__.ssl_selector` in CloudOS.

Tests are made for checking if the function ssl_selector working as intended. It tests three scenarios:
- `test_ssl_selector_disable_ssl_verification_without_ssl_cert`
- `test_ssl_selector_without_ssl_cert`
- `test_ssl_selector_with_ssl_cert`

To run the test:
```
python3 -m pytest -s -v
```

Expected Output:
<img width="741" alt="image" src="https://user-images.githubusercontent.com/25952802/205022120-3fa5e07f-f574-4dd7-a76d-eb993d948641.png">

2022-12-02 18:44 UTC, dapineyro requested changes
Thanks @egenc . Please, check my comments about the code.

In addition, could we move this script to a new folder `tests/main/` which would make more sense for this test?

2022-12-02 18:44 UTC, dapineyro commented on tests/test_clos/test_ssl_selector.py
> +
```suggestion


```

2022-12-02 18:44 UTC, dapineyro commented on tests/test_clos/test_ssl_selector.py
> +
```suggestion


```

2022-12-02 18:44 UTC, dapineyro commented on tests/test_clos/test_ssl_selector.py
> +
```suggestion


```

2022-12-02 18:44 UTC, dapineyro commented on tests/test_clos/test_ssl_selector.py
> +
```suggestion


```

2022-12-02 18:44 UTC, dapineyro commented on tests/test_clos/test_ssl_selector.py
> +
```suggestion
```

2022-12-02 18:44 UTC, dapineyro commented on tests/test_clos/test_ssl_selector.py
> +        assert True
```suggestion
    assert result is False
    assert result_string == '[WARNING] Disabling SSL verification'
    assert warnings.filters[0][0] == 'ignore'
```
Being the assertion in an `if` clause, it will not be executed if the condition is not met.
In addition, it would be good to check if the warnings were really disabled, which is the purpose of the tested function.

2022-12-02 18:44 UTC, dapineyro commented on tests/test_clos/test_ssl_selector.py
> +@supress_stdout
```suggestion
```
This is not required as you are effectively capturing the `stdout` inside the function to get the `[WARNING] Disabling...`

2022-12-02 18:44 UTC, dapineyro commented on tests/test_clos/test_ssl_selector.py
> +    result = ssl_selector(disable_ssl_verification=True, ssl_cert=None)
```suggestion
    result = ssl_selector(disable_ssl_verification=True, ssl_cert=None)
    result_string = output.getvalue().rstrip()
```
Now, changing the order, it really captures the `stdout`. Also, it removes the trailing `\n`

2022-12-02 18:44 UTC, dapineyro commented on tests/test_clos/test_ssl_selector.py
> +    return wrapper
This function could be removed as the decorator is not really needed

2022-12-02 18:44 UTC, dapineyro commented on tests/test_clos/test_ssl_selector.py
> +import contextlib
```suggestion
```
This could be removed if you are not using `supress_stdout`

2022-12-02 18:44 UTC, dapineyro commented on tests/test_clos/test_ssl_selector.py
> +from cloudos.__main__ import ssl_selector
```suggestion
from cloudos.__main__ import ssl_selector
import warnings
```
This will be required to check if warnings were really disabled.

2022-12-02 18:44 UTC, dapineyro commented on tests/test_clos/test_ssl_selector.py
> +    """testing without ssl_verification and ssl_certification"""
```suggestion
    """testing disable ssl_verification"""
```

2022-12-02 18:44 UTC, dapineyro commented on tests/test_clos/test_ssl_selector.py
> +    """testing without ssl certification"""
```suggestion
def test_ssl_selector_not_disable_verification():
    """testing not disabling ssl verification"""
```

2022-12-02 18:44 UTC, dapineyro commented on tests/test_clos/test_ssl_selector.py
> +    """testing with ssl certification"""
```suggestion
def test_ssl_selector_not_disable_verification_ssl_cert_provided:
    """testing not disabling ssl verification and providing the ssl_cert"""
```

2022-12-02 18:44 UTC, dapineyro commented on tests/test_clos/test_ssl_selector.py
> +    assert isinstance(result, str) and len(result) > 0
```suggestion
    assert isinstance(result, str) and len(result) > 0
    assert os.path.isfile(result)
```
Why to create a complete new function to test the same object. Remove the function below and add the assert here.

2022-12-02 18:44 UTC, dapineyro commented on tests/test_clos/test_ssl_selector.py
> +
```suggestion
```

2022-12-12 09:18 UTC, egenc commented
thanks for the review @dapineyro , I have made the requested changes and  I think it is ready to merge now.

2023-01-16 10:15 UTC, dapineyro approved these changes
LGTM!

2023-01-16 10:44 UTC, merged