feat: add `--request-interval` parameter
lifebit-ai/cloudos-cli pull request #93
Opened 2022-09-29 13:49 UTC by danielboloc

## Overview

It adds a new parameter `--request-interval` to the `job run` command, allowing for a custom input of time to request job completion status to the API. An example would be:

```
cloudos job run ... --wait-completion --set-interval 5
```

The constant variable `REQUEST_INTERVAL` is removed, replaced by the `--request-interval`, which has a default value of `30`. The change was also done in `cromwell start` command, to be able to remove the constant.

Issue addressed in this PR:

#90 

Link to Sprint Issue:

[CLOUDOSCLI-4](https://lifebit.atlassian.net/browse/CLOUDOSCLI-4)

## Changes
- `CHANGELOG.md`
- `README.md`
- Add `--request-interval` option
- Bump version from 1.0.0 to 1.1.0

## Test
```
docker run --rm -it quay.io/lifebitaiorg/cloudos-cli:v1.1.0

MY_API_KEY="****"
CLOUDOS="https://cloudos.lifebit.ai"
WORKSPACE_ID="****"
PROJECT_NAME="API request interval"
WORKFLOW_NAME="rnatoy"

cloudos job run \
    --cloudos-url $CLOUDOS \
    --apikey $MY_API_KEY \
    --workspace-id $WORKSPACE_ID \
    --project-name "$PROJECT_NAME" \
    --workflow-name $WORKFLOW_NAME \
    --parameter reads=s3://lifebit-featured-datasets/pipelines/rnatoy-data \
    --parameter genome=s3://lifebit-featured-datasets/pipelines/rnatoy-data/ggal_1_48850000_49020000.Ggal71.500bpflank.fa \
    --parameter annot=s3://lifebit-featured-datasets/pipelines/rnatoy-data/ggal_1_48850000_49020000.bed.gff \
    --spot \
    --wait-completion \
    --request-interval 25
```

Expected output:

```
CloudOS python package: a package for interacting with CloudOS.

Version: 1.1.0

CloudOS job functionality: run and check jobs in CloudOS.

Executing run...
	Job successfully launched to CloudOS, please check the following link: https://cloudos.lifebit.ai/app/jobs/633590c43735bf0154ac048f
	Your assigned job id is: 633590c43735bf0154ac048f
	Please, wait until job completion or max wait time of 3600 seconds is reached.
	Your current job status is: initializing.
	Your current job status is: running.

	Your job took 450 seconds to complete successfully.
```

cloudOS job: https://cloudos.lifebit.ai/app/jobs/633590c43735bf0154ac048f

2022-09-30 09:01 UTC, dapineyro requested changes
Thanks @danielboloc ! I've added some comments and suggestions. In addition to them, please, remember to create the docker container for the corresponding version and push it to quay.io

2022-09-30 09:01 UTC, dapineyro commented on cloudos/__main__.py
> +              default=30)
While is not bat to have the possibility of adjusting the request interval for the cromwell restart, this is a more fixed task, taking less than 5 minutes (300s). Therefore, the help string here is not correct. Also, if the user sets this value too high, it will cause very poor performance, as it will stay long in sleep when it's not generally required. In addition, there is the possibility that the user sets `--wait-time` smaller than `--request-interval`, which is a nonsense and should be controlled, adding:
```
if request_interval > wait_time:
    request_interval = wait_time
```

2022-09-30 09:01 UTC, dapineyro commented on cloudos/__main__.py
> +                elapsed += request_interval
The variable `request_interval` should not be the same for controlling cromwell restart here and job status below. If someone has a very long run and sets 1h for request interval, in the case of a cromwell job it will sleep far too long in cromwell restart step, degrading performance. In addition, we have hard-coded 300 seconds as wait time for cromwell. Therefore, we should add a control expression like:
```
if request_interval > 300:
    request_interval = 300
```
And also specify this in the help string

In my opinion, it is an unnecessary complication as it's not normally required to change this for Cromwell.

2022-09-30 09:01 UTC, dapineyro commented on cloudos/__main__.py
> +                elapsed += request_interval
We should add a control expression to ensure that the user has not set `--request-interval` bigger than `--wait-time`

2022-09-30 12:18 UTC, danielboloc commented on cloudos/__main__.py
> +              default=30)
Removed this option from `cromwell`

2022-09-30 12:19 UTC, danielboloc commented on cloudos/__main__.py
> +                elapsed += request_interval
I agree, now for the cromwell there is the constant `REQUEST_INTERVAL_CROMWELL`, set to 30

2022-10-03 10:30 UTC, dapineyro requested changes
Thanks @danielboloc for the changes. Only make sure that all the `request_interval` are changed to `REQUEST_INTERVAL_CROMWELL` when interacting with cromwell server

2022-10-03 10:30 UTC, dapineyro commented on cloudos/__main__.py
> +                elapsed += request_interval
@danielboloc Please, change this `request_interval` here to be `REQUEST_INTERVAL_CROMWELL`, as this piece of code is in charge of the cromwell server restart.

2022-10-03 14:35 UTC, danielboloc commented
Thank you @dapineyro for spotting this, added the change.

2022-10-03 17:03 UTC, dapineyro approved these changes
LGTM!

2022-10-03 17:08 UTC, merged